### ISSUE TITLE
when in click in index.html inside a subfolder the file is downloaded instead of just serving it

### ISSUE THREAD

**Issue by alins** [qoomon/aws-s3-bucket-browser#1]
first of all: awesome job, love what you have done here.

the way i use it is to show a list of folder where each folder have various reports from a build process (karma tests, junit, coverage..etc). navigation in and out is great, no problems there

everything works great until i get inside one of the leaf folder that has the html report

here's one example so you can see what i'm talking about

![Screen Shot 2019-11-26 at 6 21 26 PM](https://user-images.githubusercontent.com/1194699/69688020-b7441100-1079-11ea-82bd-e94be8941ea3.png)

when i click on index.html the file is downloaded...but..if i right click, copy the link and paste that into a different tab the file is served and i can see the rendered html.

i'm purely guessing this is a content type problem...any ideas how to fix it?

**Comment by qoomon** [comment]
It is by purpose but maybe you are right and I should change it, or add a button to open  the file or a dedicated button to download it. Currently I am on vacation so please create a pull request or wait until mid of December then I can fix it on my own.

**Comment by qoomon** [comment]
Try to remove line 107 and 158

**Comment by alins** [comment]
awesome!!...that worked. 

another one if you don't mind: is it possible to automatically sort by "Name" descendent?

**Comment by qoomon** [comment]
Just click the name column twice
