### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by thelegendofdeep** [qoomon/aws-s3-bucket-browser#10]
what type of license does this repo use? 

can it be used for commercial use?

**Comment by qoomon** [comment]
As long as you mention my name/website (qoomon.me) feel free to use it. I will add a proper licence within the next days.

**Comment by qoomon** [comment]
Any suggestion for a licence?

**Comment by thelegendofdeep** [comment]
MIT?

https://opensource.org/licenses/MIT

Thanks!

**Comment by qoomon** [comment]
Done!
