### ISSUE TITLE
List Bucket response does not contain <ListBucketResult> tag!

### ISSUE THREAD

**Issue by Jettzett** [qoomon/aws-s3-bucket-browser#13]
Hi,

I have set up permissions according to the instructions.

When accessing the page I get the following error:
"List Bucket response does not contain ListBucketResult tag!"

Any hints?

**Comment by qoomon** [comment]
What is the response of `https://s3.eu-west-1.amazonaws.com/data.openspending.org?list-type=2&delimiter=/&prefix=datasets/&max-keys=50` looks like?
(adjust the example url to your bucket)

It should look like the response from the example url `https://s3.eu-west-1.amazonaws.com/data.openspending.org?list-type=2&delimiter=/&prefix=datasets/&max-keys=50 looks like`

**Comment by Jettzett** [comment]
Thank you for your reply!
The output is similar. The XML lists the content of the bucket.

**Comment by Jettzett** [comment]
Thank you for your reply!

The output is quite different:

<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Name>testbucket-bucketname</Name>
<Prefix/>
<Marker/>
<MaxKeys>1000</MaxKeys>
<IsTruncated>false</IsTruncated>
<Contents>
<Key>256T.png</Key>
<LastModified>2021-02-01T21:54:44.000Z</LastModified>
<ETag>"007523460db8a2b71e000f3fbb242867"</ETag>
<Size>822</Size>
<Owner>
<ID>4b424560c1a02ff8a4da1454151a3c9791900aebc803aa243fcc52022a075124</ID>
</Owner>
<StorageClass>STANDARD</StorageClass>
</Contents>
<Contents>
<Key>file.html</Key>
<LastModified>2021-02-01T22:52:07.000Z</LastModified>
<ETag>"6d007062899f2239a1b272468a5edb73"</ETag>
<Size>5611</Size>
<Owner>
<ID>4b424560c1a02ff8a4da1454151a3c9791900aebc803aa243fcc52022a075124</ID>
</Owner>
<StorageClass>STANDARD</StorageClass>
</Contents>

(.....)

**Comment by qoomon** [comment]
at [these lines](https://github.com/qoomon/aws-s3-bucket-browser/blob/b846d5bf8447e6c29ed1a5e5e03d6514148a89f5/index.html#L288) I do the check. I can't see any problems.

May you can have a look at browser consoles network tab to debug the request and corresponding response to the bucket enpoint.

**Comment by qoomon** [comment]
Do you host the S3 Bucket Browser HTML file a the same domain as the bucket? If so, do you allow CORS access to your bucket?

**Comment by qoomon** [comment]
Grant Cross Origin Access by `CORS Configuration`
    ```json
    [
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "http://www.example.com"
        ],
        "ExposeHeaders": [
            "x-amz-server-side-encryption",
            "x-amz-request-id",
            "x-amz-id-2"
        ],
        "MaxAgeSeconds": 3000
    }
    ]
    ```

**Comment by Jettzett** [comment]
It is hosted on the same domain, so it should not be necessary with CORS config :-)
I cant see any problems in the console.

This bucket is hosted in eu-north, could there be policy differences between S3 regions?

**Comment by qoomon** [comment]
so even in network tab you can see the right request and response?

**Comment by qoomon** [comment]
if its a public bucket you may provide me the url so I can debug it.

**Comment by BelyashUa** [comment]
I had the same issue.
The reason was that I used the Bucket website endpoint instead of the Bucket URL.
Use  **https://s3.amazonaws.com/Bucket-NAME/index.html** instead of **http://Bucket-NAME.s3-website-us-east-1.amazonaws.com**.
