### ISSUE TITLE
CloudFront support

### ISSUE THREAD

**Issue by BelyashUa** [qoomon/aws-s3-bucket-browser#14]
Hi and thank you for this project.

I have set up it on S3 and it works.
But I want to use CloudFront. I have configured CF as you discribe  it in README.md.

When I open CF url it shows me an error: `List bucket response does not contain <ListBucketResult> tag!`

According to message in footer its tries to use CF url instead of real bucket url.
![image](https://user-images.githubusercontent.com/9842617/107033758-6d4ad500-67be-11eb-815d-4623319ee70d.png)
And the same situation when I use my domain from route 53.

Maybe I did somting wrong..

**Comment by qoomon** [comment]
I see, this is because the script tries to determine bucket url by getting it from index.html url.

I think easiest solution is to provide a config variabel to override this behavior.

**Comment by BelyashUa** [comment]
Thank you for reply.
What config variabel shell I provide ?

I have tested it with 'bucketUrl' in the index.html

![image](https://user-images.githubusercontent.com/9842617/107248057-9b3c4d80-6a3a-11eb-9303-554143cf287c.png)

but it does not help. 

Also with this configuration I had an error when opend  bucked url directly 
![image](https://user-images.githubusercontent.com/9842617/107247843-616b4700-6a3a-11eb-950a-22550272a9d1.png)

**Comment by qoomon** [comment]
hi, first of all `bucketUrl` is the right config variable. I think your bucket url is wrong you need to provide bucket location like this `https://s3.${region}.amazonaws.com/...`. However I don't understand why you get this reference error, I never get it. I assume its because of an evaluation order problem. I'll try to add `defer ` attribute to config script. Give me a minute.

**Comment by qoomon** [comment]
Oh defer attribute is not valid for inline scripts. Do you get the reference error all the time?

**Comment by qoomon** [comment]
Is my example working on your machine? https://qoomon.github.io/aws-s3-bucket-browser/index.html?bucket=https://s3.eu-west-1.amazonaws.com/data.openspending.org

**Comment by qoomon** [comment]
this example set bucketUrl by request parameter otherwise it should work the same way as if you set bucketUrl statically within the config object.

**Comment by BelyashUa** [comment]
>  Do you get the reference error all the time?
no, just in case when I set up `bucketUrl` in the index.html. Otherwise, it works fine.

**Comment by BelyashUa** [comment]
> Is my example working on your machine? https://qoomon.github.io/aws-s3-bucket-browser/index.html?bucket=https://s3.eu-west-1.amazonaws.com/data.openspending.org

**Comment by BelyashUa** [comment]
> > Is my example working on your machine? https://qoomon.github.io/aws-s3-bucket-browser/index.html?bucket=https://s3.eu-west-1.amazonaws.com/data.openspending.org
> 
> I can open your site, but when I passed my S3 URL have an error
> ![image](https://user-images.githubusercontent.com/9842617/107264620-da26cf00-6a4b-11eb-8729-2352fcf7595f.png)
> 
> This is my S3 URL
> `https://s3.amazonaws.com/d2dpqoe4o8lq65.cloudfront.net/`

I fixed this error in the CORS setting, but still, have an error 
![image](https://user-images.githubusercontent.com/9842617/107266484-44407380-6a4e-11eb-90ac-2035f31f20d4.png)

**Comment by qoomon** [comment]
you bucket url end in a file `.../caarefirsl.txt` that seems wrong.

**Comment by qoomon** [comment]
I get a bucket not found error if I try to reach `https://s3.amazonaws.com/d2dpqoe4o8lq65.cloudfront.net/`

**Comment by qoomon** [comment]
the region is missing again in your bucket url `https://s3.amazonaws.com/d2dpqoe4o8lq65.cloudfront.net/`

**Comment by BelyashUa** [comment]
I did some testing and create a new bucket. Now your example is working for me:
**_https://qoomon.github.io/aws-s3-bucket-browser/index.html?bucket=https://s3.us-east-1.amazonaws.com/gttbdownloads.com_**

But from CF it still tries to use CF URL.

**Comment by qoomon** [comment]
for me following `index.html` works as expected. I set your bucket url as bucketUrl within config section see [index.html.zip](https://github.com/qoomon/aws-s3-bucket-browser/files/5948161/index.html.zip)

**Comment by BelyashUa** [comment]
I checked your index.html and finally its start to work.  For CF with Route 53 it also works.

Thanks for the help !

**Comment by qoomon** [comment]
you're welcome.
