### ISSUE TITLE
bucket directory listing is not working

### ISSUE THREAD

**Issue by bvijaycom** [qoomon/aws-s3-bucket-browser#15]
in index.html file after replaced the following line also 

bucketUrl: 'http://bucket-name.s3-website-eu-west-1.amazonaws.com'

please help on where i am missing it.

![listbucketresult-error](https://user-images.githubusercontent.com/10959871/111670707-6af58500-8818-11eb-8988-e37f121bff70.JPG)

**Comment by qoomon** [comment]
I need some more information. The bucket url 'http://bucket-name.s3-website-eu-west-1.amazonaws.com' seems to be wrong I got 
```
Code: IncorrectEndpoint
Message: The specified bucket exists in another region. Please direct requests to the specified endpoint.
Endpoint: bucket-name.s3-website-us-east-1.amazonaws.com
```
further more bucket url format should be like 'https://s3.eu-west-1.amazonaws.com/data.openspending.org' in your case probably 'https://s3.us-east-1.amazonaws.com/bucket-name'

**Comment by qoomon** [comment]
the `bucketUrl` should return an xml with `<ListBucketResult>` as root element, see 'https://s3.eu-west-1.amazonaws.com/data.openspending.org'

**Comment by bvijaycom** [comment]
actual bucket name is http://dgenv-website1.s3-website-eu-west-1.amazonaws.com/ (this is the name  i got  when i enabled the static website hosting in s3 bucket properties).I have attached the static website dns name screenshot also from s3 bucket properties.

here i have attached the index.html file in index.zip file format. please help me what i am doing wrong here


![static-website-name](https://user-images.githubusercontent.com/10959871/111689884-d6e1e880-882c-11eb-8f2f-0c5f81e1f6af.JPG)
[index.zip](https://github.com/qoomon/aws-s3-bucket-browser/files/6166897/index.zip)

**Comment by qoomon** [comment]
change `bucketUrl` to `https://s3.eu-west-1.amazonaws.com/dgenv-website`

**Comment by bvijaycom** [comment]
bucket name is dgenv-website1 so shall i put like below

https://s3.eu-west-1.amazonaws.com/dgenv-website1

?

**Comment by qoomon** [comment]
yes that would work.

I also added a feature to handle those website se3 bucket addresses out of the box. just leave `bucketUrl` undefined and it should work aswell.

**Comment by bvijaycom** [comment]
Now this below s3 bucket url is working

http://dgenv-website.s3-website-eu-west-1.amazonaws.com/


However if i access actual domain name https://env.dataplatform.tech.ec.europa.eu/  then always calling wrong url 

Bucket: https://s3.eu-west-1.amazonaws.com/dgenv-website

can you help me on this

**Comment by qoomon** [comment]
this is because of your CORS setup, see (CORS Configuration in README)[https://github.com/qoomon/aws-s3-bucket-browser#hosted]

**Comment by qoomon** [comment]
set AllowedOrigins to your hosting domain in your case  https://env.dataplatform.tech.ec.europa.eu

**Comment by bvijaycom** [comment]
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "https://env.dataplatform.tech.ec.europa.eu/"
        ],
        "ExposeHeaders": [
            "x-amz-server-side-encryption",
            "x-amz-request-id",
            "x-amz-id-2"
        ],
        "MaxAgeSeconds": 3000
    }
]


I have implemented the above CORS rule in the s3 bucket permission.Still whenever i access the https://env.dataplatform.tech.ec.europa.eu/ and it is trying to access wrong S3 bucket below url


wrong url - Bucket: https://s3.eu-west-1.amazonaws.com/dgenv-website

correct url - http://dgenv-website.s3-website-eu-west-1.amazonaws.com


i think index.html is still working old S3 bucket name format.Can you please check and advise me

**Comment by qoomon** [comment]
'https://s3.eu-west-1.amazonaws.com/dgenv-website' <- this url is your bucket url, it is the right one.

**Comment by qoomon** [comment]
i get a 404 when I open https://env.dataplatform.tech.ec.europa.eu/index.html

**Comment by qoomon** [comment]
do you need any further support?
