### ISSUE TITLE
Feature request - specify default ordering

### ISSUE THREAD

**Issue by antaenc** [qoomon/aws-s3-bucket-browser#22]
In the config section ability to choose which column to order on and ordering direction so this is presented upon loading index.html without having to click on the column to obtain desired ordering.

**Comment by qoomon** [comment]
Seams reasonable

**Comment by qoomon** [comment]
FYI the S3 Bucket API does not provide any feature to sort while querying. That means you can only sort current page of S3 items.

**Comment by qoomon** [comment]
done. there is a new option `config.defaultOrder'` e.g. `config.defaultOrder='name-asc'`

**Comment by antaenc** [comment]
Thank you!
