### ISSUE TITLE
Feature Request - Render Markdown File(s)

### ISSUE THREAD

**Issue by ghost** [qoomon/aws-s3-bucket-browser#25]
Hello, @qoomon! Great job making this script!

I've forked your repository and added my personal setup to list all of my bucket files on my S3-compatible storage. So far, everything work as expected.

But I have an idea:  **Rendering markdown on the site**.

For example, we have README.md. We could render it after the file list. It is very useful for people that wants viewable documentation.

I found a script related to this:

- https://zerodevx.github.io/zero-md/

Based on this StackOverflow answer: https://stackoverflow.com/a/60363693/13293193

Thanks!

**Comment by qoomon** [comment]
Interesting. I'm not sure whether I'll find time for that.  However every PR is welcome.

**Comment by qoomon** [comment]
Should work now.
