### ISSUE TITLE
not working url

### ISSUE THREAD

**Issue by upintheairsheep** [qoomon/aws-s3-bucket-browser#28]
http://cds.p6v7v3q9.hwcdn.net/

**Comment by qoomon** [comment]
could you explain a little more what is your issue?

**Comment by qoomon** [comment]
some findings so far your url `http://cds.p6v7v3q9.hwcdn.net`
* no https
* its not a s3 bucket api, e.g. `http://cds.p6v7v3q9.hwcdn.net/?list-type=2&delimiter=/&prefix=&max-keys=2` is not consider `max-keys=2`

**Comment by qoomon** [comment]
@upintheairsheep ?

**Comment by upintheairsheep** [comment]
I'm here I want a script that will convert whatever the heck this is to a
txt file with 1 url per line. This can be done by appending the "Key" of
each xml part to the url, like hwcdn for me. Then give me the script and
the output. Especially the output.

**Comment by qoomon** [comment]
I don't get what you want. I think bucket explorer is not what you are looking for.
