### ISSUE TITLE
Direct link to "folders"

### ISSUE THREAD

**Issue by JulianGro** [qoomon/aws-s3-bucket-browser#29]
The ability to link to "folders" would be nice.

Currently when I link to https://public.overte.org/index.html#build/overte/ it just shows the root of the bucket instead of /build/overte/

**Comment by qoomon** [comment]
you are totally right, I'll fix it

**Comment by qoomon** [comment]
should be fixed

**Comment by JulianGro** [comment]
Seems to work.
I cannot update the file on the S3 right now because the S3 is somehow broken currently, but it works if I just open the same index.html with the changes from 1.8.1
