### ISSUE TITLE
ListBucketResponse error rendering on index.html

### ISSUE THREAD

**Issue by pschloss** [qoomon/aws-s3-bucket-browser#3]
I'm trying to implement your bucket viewer, but am hitting the error at https://github.com/qoomon/aws-s3-bucket-browser/blob/master/index.html#L313. Do you have any insights as to what I might be doing wrong? My index page is at https://mothur.s3.us-east-2.amazonaws.com/index.html.

**Comment by qoomon** [comment]
probably your bucket does not have the right permissions.

How does the response of following Url looks like, `<YOUR BUCKET URL>?list-type=2`

e.g. `https://s3.eu-west-1.amazonaws.com/data.openspending.org?list-type=2`

It should contains following element `<ListBucketResult>... </ListBucketResult>`

**Comment by pschloss** [comment]
Thanks, that was the problem!

**Comment by qoomon** [comment]
@pschloss I've added some documentation how to setup needed permissions to [README](https://github.com/qoomon/aws-s3-bucket-browser/blob/master/README.md)

**Comment by coolbeans321** [comment]
Hi, I have a similar problem outlined above. The link with adding `<YOUR BUCKET URL>?list-type=2` yields the element `<ListBucketResult>... </ListBucketResult>`. However, I get a page with an empty directory listing. For context, I'm not sure that it matters, but if it does, I'm using CloudFront with route53. What would you suggest to resolve this?

**Comment by qoomon** [comment]
@coolbeans321 my app works with direct access to s3 bucket address. I don't know how cloudfront affects calls to s3 buckets. Maybe it does not proxy the whole request or you having trouble with caching by cloudfront.

**Comment by coolbeans321** [comment]
I just tried disabling object caching, but that didn't seem to do the trick. What do you mean by not proxying the full request?

**Comment by qoomon** [comment]
@coolbeans321 could you post an example response from cloudfront? I think the behaviours of direkt s3 access and cloudfront are different because cloudfront uses another s3 url than the s3 api url.  However if you provide me an response example and a public test cloudfront setup I could update this webapp to support cloudfront setup as well.

**Comment by qoomon** [comment]
there are multiple urls to access an s3 bucket
* https://s3-eu-west-1.amazonaws.com/data.openspending.org?list-type=2
  * -> valid response
* http://data.openspending.org.s3.amazonaws.com/?list-type=2
  * -> valid response, however no https support 
* http://data.openspending.org.s3-website-eu-west-1.amazonaws.com?list-type=2
  * -> invalid response, it renders a default directory listing. parameter list-type is ignored
  * this type of url might be used by cloudfront

**Comment by qoomon** [comment]
@coolbeans321 may you provide the index.html url you use and`config.bucketUrl` if you set it manually?
