### ISSUE TITLE
first time visit does not browse into given path prefix provided in url

### ISSUE THREAD

**Issue by pasenau** [qoomon/aws-s3-bucket-browser#30]
When entering an url like https://s3-bukcet.eu-west-1.amazonaws.com/#myFolder/second-one/ it shows the home folder https://s3-bukcet.eu-west-1.amazonaws.com/# instead of the contents of https://s3-bukcet.eu-west-1.amazonaws.com/#myFolder/second-one/ .

Here is the patch: just adding a new line and changing another: 

[index.html.patch.txt](https://github.com/qoomon/aws-s3-bucket-browser/files/8415779/index.html.patch.txt)

Thanks for the tool!

**Comment by qoomon** [comment]
which version do you use? because it works already, see https://qoomon.github.io/aws-s3-bucket-browser/index.html?bucket=https://s3.eu-west-1.amazonaws.com/data.openspending.org#worldbank/

**Comment by pasenau** [comment]
Hi Qoomon, i was using version 1.8.0 with a S3 bucket behind CloudFront. Adding the two lines, worked for me.
Will try the new version without the addition.

**Comment by qoomon** [comment]
Please reopen if you still facing this bug in version `1.8.1`
