### ISSUE TITLE
rootPrefix folder is visible on every page. It should be hidden.

### ISSUE THREAD

**Issue by Dhyanesh97** [qoomon/aws-s3-bucket-browser#34]
rootPrefix folder is visible on every screen on the top. Need to hide it on every page.

It confuses users and they treats it as subfolder. When we click on it nothing shows up.

**Comment by qoomon** [comment]
Could you post a screenshot? I'm not sure what is the problem.

**Comment by qoomon** [comment]
could you try latest version `1.8.3` https://github.com/qoomon/aws-s3-bucket-browser/blob/master/index.html

**Comment by qoomon** [comment]
should be fixed in latest version `1.8.4`

**Comment by Dhyanesh97** [comment]
Latest version 1.8.3 solved the issue

**Comment by Dhyanesh97** [comment]
Could you also add search bar at the top which can help users to search quickly ?

**Comment by qoomon** [comment]
could you open another issue for that? I'll close this one.
