### ISSUE TITLE
Add search bar at the top which can help users to search files quickly

### ISSUE THREAD

**Issue by Dhyanesh97** [qoomon/aws-s3-bucket-browser#35]
Could you add search bar at the top which can help users to search files quickly ?

**Comment by qoomon** [comment]
Hi @Dhyanesh97 a real search is not possible with s3 api, however a prefix search is possible. I'll try to add it during the next days.

**Comment by qoomon** [comment]
have look at latest version `1.9.0`, it has a search bar now.

**Comment by qoomon** [comment]
@Dhyanesh97 WDYT?

**Comment by Dhyanesh97** [comment]
@qoomon I had discussion internally and am not sure if users are going to search based on prefixes.
File based search is what everyone is interested in. We will have thousands of files in folder. File based search could really help in this scenario.
If you can introduce this feature it could be really helpful.

**Comment by qoomon** [comment]
This is not possible with the bucket api, sorry

**Comment by qoomon** [comment]
you would need to index the whole bucket within a database.
