### ISSUE TITLE
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

### ISSUE THREAD

**Issue by Dhyanesh97** [qoomon/aws-s3-bucket-browser#36]
![image](https://user-images.githubusercontent.com/89400147/165232792-6751fc6b-f64a-4fe4-ab34-c3c543c4ef01.png)

I have configured s3 Static website + CloudFront with lambda@Edge + aws cognito. 
When I open Cloudfront URL after authenticating with cognito it shows above errors that it is not able to load the page due to security issues.

Link to refer: https://medium.com/@saurishkar/setting-up-aws-http-authentication-on-cloudfront-s3-using-cognito-and-lambda-edge-166ee38d471e

added below line to HTML but still gives an error.
```
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' * ">
```

![image](https://user-images.githubusercontent.com/89400147/165245075-6ff84557-242c-47d2-94e7-b388b70b03d3.png)

Any help appreciated.

**Comment by qoomon** [comment]
I thnik this is not related to this project, it is rather a general problem. You could open an [stackoverflow](https://stackoverflow.com/) question.

**Comment by tcarrondo** [comment]
@Dhyanesh97 see if this helps:
https://github.com/aws-samples/cloudfront-authorization-at-edge/issues/197
https://github.com/aws-samples/cloudfront-authorization-at-edge/issues/73
