### ISSUE TITLE
Bucket has to be public in order to work with s3-bucket-brower ?

### ISSUE THREAD

**Issue by Dhyanesh97** [qoomon/aws-s3-bucket-browser#37]
Bucket has to be public in order to work with s3-bucket-brower ?

I have added CORS Configuration and bucket policy. But anyone can download files within the bucket programmatically. 

Use Case: Implemented s3-static-website + cloud-front with labda@Edge + aws congnito.
cloud-front url is authenticated with cognito to show the static-website.

Even though we have enable authentication at browser level for static website, files can be accessed programmatically from anywhere.

Could you please suggest a way how we can restrict the same ?

**Comment by qoomon** [comment]
Currently there is no support for private buckets.

**Comment by karansinghpannu** [comment]
Thank you for this project, it is brilliant.

I was able to get this working with a private S3 bucket sitting behind  Cloudfront + WAF with an IP block rule to only allow certain IP addresses

In the index.html, adding the cloudfront URL value to the bucketURL worked 

` bucketUrl: 'https://<something>.cloudfront.net` 

Of-course i had to make other changes as described in the readme.
Thank you for this project

**Comment by qoomon** [comment]
Glad to hear that.

**Comment by tcarrondo** [comment]
@karanaizen can you elaborate your solution for serving private buckets?

**Comment by karanaizen** [comment]
hey @tcarrondo 

I added notes on how to fix this above:
in short i used CloudFront + AWS WAF. The WAF is used to only allow access to CloudFront via allowed IP's

In the index.html, add the cloudfront URL value to the bucketURL.

`bucketUrl: 'https://<something>.cloudfront.net`
