### ISSUE TITLE
%2F delimeters in href 

### ISSUE THREAD

**Issue by reqlez** [qoomon/aws-s3-bucket-browser#38]
I'm getting %2F delimeters generated in the path to the file, like:

root%2Fanotherfolder%2Ffile.jpeg  instead of 
root/anotherfolder/file.jpeg

This is making the browser save the file as "root_anotherfolder_file.jpeg" filename instead of "file.jpeg" filename.

Can this be controlled somewhere? I saw another site with an older version, where it's as what i'm trying to get, but seems latest version is different? or am i missing something?

**Comment by qoomon** [comment]
You're right these delimiters `%2F` could and should be replaced by just `/`, however I can't reproduce the wrong behavior in Chrome browser. What browser do you use? I'll try to fix it anyway, because it looks ugly also on chrome :-)

**Comment by qoomon** [comment]
On safari I can reproduce your issue.

**Comment by qoomon** [comment]
I fixed it, please try again

**Comment by reqlez** [comment]
Oh wow, I was not watching this ticket since i did not think you would get back to me so fast!

Thanks! That was the fix! Working great now :)

**Comment by korhox** [comment]
Hi!

I have the same issue in version 1.9.2. I'm on macOS (M1 + Ventura beta) and the issue is between all browsers (Safari, Chrome & Firefox)


Offtopic: This is so far the Best and the simplest s3 browser I've ever used.

**Comment by qoomon** [comment]
Hi @korhox thanks for reporting.

Unfortunately I'm not able to reproduce this behaviour.

Could you provide an example `href` value? The only possible reason I can imagine is that `encodeURI('foo/bar')` behaves different, maybe you can run this code in your browser console an check the output. The expected result should be `foo/bar`.

**Comment by korhox** [comment]
Hello!

Here's a screenshot from the inspector:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/10478812/194320631-621fa4d7-0293-482a-91d8-9fce506c0ba7.png">

And weirdly enough, `encodeURI('foo/bar')` works as excepted:
<img width="181" alt="image" src="https://user-images.githubusercontent.com/10478812/194320968-a51ea39a-9aaa-4f6d-9f1b-59058acb246b.png">

**Comment by korhox** [comment]
I went through your code, it seems you are using `encodeURIComponent` instead of `encodeURI`. I changed this to `encodeURI` on my end and now it works.
<img width="235" alt="image" src="https://user-images.githubusercontent.com/10478812/194321672-44c6d0ea-c129-482a-925a-b7ee5fa75849.png">

**Comment by qoomon** [comment]
oh :-) you're not using the latest version `1.10.1` https://github.com/qoomon/aws-s3-bucket-browser/blob/master/index.html
