### ISSUE TITLE
issue with ssl

### ISSUE THREAD

**Issue by ufukayyildiz** [qoomon/aws-s3-bucket-browser#39]
hi,

this works great with http://mydomain...

but returns failed to fetch with **https**://mydomain... 

thanks.

![image](https://user-images.githubusercontent.com/23309320/178865779-88a8a38c-10f6-42d0-a52d-04acc695643c.png)

**Comment by qoomon** [comment]
following usage works (host and bucket url are HTTPS urls)
* https://qoomon.github.io/aws-s3-bucket-browser/index.html?bucket=https://s3.amazonaws.com/spacenet-dataset#spacenet/
* following usage will NOT works (host url is HTTPS and bucket url is just HTTP) 
https://qoomon.github.io/aws-s3-bucket-browser/index.html?bucket=http://s3.amazonaws.com/spacenet-dataset#spacenet/
