### ISSUE TITLE
Question: ListObjects / ListObjectsV2

### ISSUE THREAD

**Issue by KoalaBear84** [qoomon/aws-s3-bucket-browser#42]
Hi qoomon,

Sorry for contacting you this way, but maybe you have more experience with this I hope. Was trying your Bucket Browser and got the Failed to fetch because or CORS, that's fine because that's only in the browser.

I was trying to implement something related to Amazon S3 and got stuck.
https://github.com/KoalaBear84/OpenDirectoryDownloader/issues/132

The issue is that maybe the marker parameter isn't supported on some hosts?

If you have any experience or info about this, thanks!

**Comment by qoomon** [comment]
I think you should use `continuation-token` query parameter instead of `marker`https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestSyntax:~:text=Required%3A%20Yes-,continuation%2Dtoken,-ContinuationToken%20indicates%20Amazon

**Comment by KoalaBear84** [comment]
Thanks, sorry for not replying earlier.

Yes, but it looks like this one doesn't support the list-type=2 parameter, and also doesn't respond as it should when I use the marker.

Do you have any experience with this?

**Comment by qoomon** [comment]
sadly I don't know how to help you with that issue.
