### ISSUE TITLE
Issues with listing subdirectories

### ISSUE THREAD

**Issue by sithtoast** [qoomon/aws-s3-bucket-browser#44]
I'm hosting a static site on S3. The root of the bucket has an index.html file, but there are a few subdirectories where a listing is needed. I've tried a smattering of things but none seem to work. I get the error 

`Bucket URL http://dk.toastednet.org.s3-website-us-east-1.amazonaws.com/CM400A/ is not a valid bucket API URL, response does not contain <ListBucketResult><Delimiter> tag.`

Can you take a look at it for me and tell me what's wrong? I have several other directories I would like to list so I can apply what I learn here to those :)

     `bucketUrl: undefined,
      // If bucketUrl is undefined, this script tries to determine bucket Rest API URL from this file location itself.
      //   This will only work for locations like these
      //   * https://s3.BUCKET-REGION.amazonaws.com/BUCKET-NAME/index.html
      //   * http://BUCKET-NAME.s3-website-BUCKET-REGION.amazonaws.com/index.html
      //   * https://storage.googleapis.com/BUCKET-NAME/index.html
      //   * https://BUCKET-NAME.s3-web.BUCKET-REGION.cloud-object-storage.appdomain.cloud/
      // If bucketUrl is set manually, ensure this is the bucket Rest API URL, e.g.
      //   * https://s3.BUCKET-REGION.amazonaws.com/BUCKET-NAME
      //   * https://storage.googleapis.com/BUCKET-NAME
      //   The URL should return an XML document with <ListBucketResult> as root element.
      rootPrefix: 'CM400A/', // e.g. 'subfolder/'
      keyExcludePatterns: [/^index\.html$/],
      pageSize: 50,

      bucketMaskUrl: undefined,
      // If bucketMaskUrl is set file urls will be changed from ${bucketUrl}/${file} to ${bucketMaskUrl}/${file}
      //   bucketMaskUrl: 'https://example.org'
      //     => https://example.org/foo/bar.txt
      //   bucketMaskUrl: document.location.origin
      //     => ${document.location.origin}/foo/bar.txt

      defaultOrder: 'name-asc' // (name|size|dateModified)-(asc|desc)
    }`

Thank you!

**Comment by qoomon** [comment]
should be fixed. bucket names with dot were not handled correctly. feel free to try version `1.11.2`

**Comment by sithtoast** [comment]
I'm not seeing any difference. :( Am I missing something or configuring it wrong? I have ACLs set and the bucket policy set.

**Comment by qoomon** [comment]
@sithtoast it is another problem now. 

```
Access to fetch at 'http://s3.us-east-1.amazonaws.com/dk.toastednet.org?list-type=2&delimiter=/&prefix=dk.toastednet.org/&max-keys=50' from origin 'http://dk.toastednet.org.s3-website-us-east-1.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

You need to setup your CORS policy. Have a look at `CORS Configuration` in [README.md](https://github.com/qoomon/aws-s3-bucket-browser#readme)

**Comment by qoomon** [comment]
* Go to `https://s3.console.aws.amazon.com/s3/buckets/<YOUR BUCKET NAME>/?tab=permissions`
  * Grant Cross Origin Access by following `CORS Configuration`
    ```json
    [
      {
          "AllowedHeaders": [
              "*"
          ],
          "AllowedMethods": [
              "GET"
          ],
          "AllowedOrigins": [
              "http://dk.toastednet.org.s3-website-us-east-1.amazonaws.com"
          ],
          "ExposeHeaders": [
              "x-amz-server-side-encryption",
              "x-amz-request-id",
              "x-amz-id-2"
          ],
          "MaxAgeSeconds": 3000
      }
    ]
    ```

**Comment by qoomon** [comment]
Hope that helps

**Comment by qoomon** [comment]
seem to work now http://dk.toastednet.org.s3-website-us-east-1.amazonaws.com/CM400A/

**Comment by sithtoast** [comment]
Sorry for responding again. I was wondering if there was a way to just list the subdirectory that the index file is placed in. Right now it's listing the root and everything in it.

**Comment by qoomon** [comment]
> Sorry for responding again. I was wondering if there was a way to just list the subdirectory that the index file is placed in. Right now it's listing the root and everything in it.

@sithtoast try version `1.11.3`
