### ISSUE TITLE
A way to change {bucket].s3-website.us-east-1. to just the site/domain we are hosting?

### ISSUE THREAD

**Issue by sithtoast** [qoomon/aws-s3-bucket-browser#45]
This might be out of scope of this project, but i was wondering if there was a way to access the index by going to say... 
dk.toastednet.org/CM400A instead of http://dk.toastednet.org.s3-website-us-east-1.amazonaws.com/CM400A/#

Would that be a DNS record of some kind?

**Comment by qoomon** [comment]
Sure you just need to create a CNAME record for dk.toastednet.org pointing to dk.toastednet.org.s3-website-us-east-1.amazonaws.com

**Comment by qoomon** [comment]
see https://www.freecodecamp.org/news/cjn-how-to-point-your-domain-to-s3-website-bucket/

**Comment by qoomon** [comment]
if you host your `index.html` under custom domain you need to set following options in the setup section
```js
const config = {
      // ...
      bucketUrl: 'http://dk.toastednet.org.s3-website-us-east-1.amazonaws.com/CM400A/',
      // ...
      bucketMaskUrl: document.location.origin,
}
```

**Comment by sithtoast** [comment]
It's all up on S3. Nothing external from that. Does that change anything?

**Comment by qoomon** [comment]
no, just set the config as described above.

**Comment by qoomon** [comment]
and adjust you CORS policy to `http://dk.toastednet.org`

**Comment by sithtoast** [comment]
I now get a blank page. It won't let me set a CNAME without removing the A record that Amazon set when I created the bucket.

**Comment by qoomon** [comment]
you forgot to quote the value `bucketUrl: 'http://dk.toastednet.org.s3-website-us-east-1.amazonaws.com/CM400A/',`

**Comment by qoomon** [comment]
http://dk.toastednet.org/CM400A/ is already working so no CNAME needed

**Comment by sithtoast** [comment]
Coming in clutch. Thanks!!!

**Comment by qoomon** [comment]
It's working now. btw I fixed the integrity check for zero-md script in version `1.11.5`
