### ISSUE TITLE
Does keyExcludePatterns exclude folders?

### ISSUE THREAD

**Issue by jackngai** [qoomon/aws-s3-bucket-browser#5]
Awesome browser! Way nicer than what I seen out there. 

I have been playing with the keyExcludePatterns and I can't seem to exclude folders. Is it supported?

**Comment by qoomon** [comment]
Actually s3 does not know the concept of folders, every file has a key "absolute file path"
may you can provide the regex and the key "absolute folder path" that does not match?

**Comment by strat1111** [comment]
Firstly thanks a lot for this, but I'm having the same issue. I can hide files but not "folders"

For example I have the following:
CBA_Driver/
index.html
index1.html

If I use 

keyExcludePatterns: [ /^index*/ ]

it hides both of the index.html files as I would expect. However if I try 

keyExcludePatterns: [ /^CBA*/ ],

it hides the files **in** CBA_Driver but not the actual folder from showing up.  Is it possible to hide the folder and everything in it?

**Comment by strat1111** [comment]
I (think) I've fixed this and added a pull request...

**Comment by qoomon** [comment]
Thx for your PR. I've merged them already 😁
