### ISSUE TITLE
Improved directory listing experience with CloudFront Functions

### ISSUE THREAD

**Issue by gw0** [qoomon/aws-s3-bucket-browser#54]
In a self-hosted scenario, it is a bit off that one has to expose the S3 website (to host `index.html`) and S3 REST API endpoints (to get the XML listing), then configure CORS rules accordingly. A much cleaner solution can be accomplished if everything is behind CloudFront (this is also the only way to use your own domain with valid TLS certificates)...

You only need to expose the S3 REST API (disable website mode) to your CloudFront distribution (using CloudFront Origin Access Controls), upload a correctly configured AWS S3 Bucket Browser into `/s3-browser/`, and use the following CloudFront Function to rewrite a few URLs. To support directory index listing I also modified to get the pathPrefix from "document.location.pathname" as a fallback.

```
-      bucketUrl: undefined,
-      keyExcludePatterns: [/^index\.html$/, /^Urban_3D_Challenge\//], // matches againt object key relative to rootPrefix
-      bucketMaskUrl: undefined,
+      bucketUrl: '/list-objects',
+      keyExcludePatterns: [/^s3-browser\//],
+      bucketMaskUrl: '/',

-        window.onpopstate = () => this.pathPrefix = decodeURIComponent(window.location.hash).replace(/^#/, '')
+        window.onpopstate = () => this.pathPrefix = decodeURIComponent(window.location.hash).replace(/^#/, '') || decodeURIComponent(window.location.pathname).replace(/^\//, '')
```

```js
/**
 * Rewrite root and directory index to an S3 bucket browser web app using AWS CloudFront Functions.
 */

var s3ListingUri = "/";
var s3BrowserUri = "/s3-browser/index.html";

function handler(event) {
  var request = event.request;

  if (request.uri == '/list-objects') {
    // Request for XML listing points to the S3 root listing endpoint
    //   https://bucket.domain/list-objects
    request.uri = s3ListingUri;

  } else if (request.uri.endsWith('/')) {
    // Request for root or directory index points to the S3 browser
    //   https://bucket.domain/
    //   https://bucket.domain/my/path/
    request.uri = s3BrowserUri;
  }

  return request;
}
```

**Comment by qoomon** [comment]
Thanks for this hosting idea.

**Comment by x3LPh0r** [comment]
Hi @gw0 thank you for the insight on this. I am looking to utilize bucket browser on a private bucket and came across this post. I performed your recommendations above with the index code edits and created the cf function and applied it to the viewer request, however I get the same error(s) I've been having trying to get a private bucket to work:

Bucket URL /list-objects is not a valid bucket API URL, response does not contain <'ListBucketResult'><'Delimiter'> tag.

Curious if I'm missing something with your recommendation or if there are any other changes that need to take place to get this to work successfully. Appreciate it.

**Comment by gw0** [comment]
> Bucket URL /list-objects is not a valid bucket API URL, response does not contain <'ListBucketResult'><'Delimiter'> tag.

It seems your CF Function is not enabled correctly. The purpose of the CF Function is to rewrite the URL `/list-objects` to `/`. The response you get when listing `/list-objects` with the CF Function **enabled** should be the same as the response you get when listing `/` with CF function **disabled**.

**Comment by x3LPh0r** [comment]
Thank you for the response. Interesting. I've tried I feel like every combination of configuration/settings possible and I get the same error message every time. Perhaps something has changed where this does not work today as it did previously. I also tried other methods entering the cloudfront domain in the bucket url setting as another person had previously which throws the same error just with the domain. 

Few screenshots attached. I tried both legacy cache settings and the new recommended with the appropriate headers. I tried OAI first (as I was using it from the previous mentioned test from another person) and switched to OAC and updated the policies for both listing and getting the bucket. I tried both js-2.0 and js-1.0 for the cf function.  I do see invocations present in the function metrics. Continuosly the same error present on the web page gui. Seems like the only way I can get it to work is making it public without OAC running it as a static website (which of course I want to avoid). 

![4](https://github.com/qoomon/aws-s3-bucket-browser/assets/37185947/abfe52a5-8ff4-4a84-8bf4-0e9f61944fd9)
![5](https://github.com/qoomon/aws-s3-bucket-browser/assets/37185947/7df34d30-d02b-4fb9-8e59-95ce2d3a6712)
![6](https://github.com/qoomon/aws-s3-bucket-browser/assets/37185947/da2eb4c1-dcca-4b5f-9b7d-6f2a45ab9878)

Do you have this functioning today on your end?  Thanks again.

**Comment by gw0** [comment]
> Do you have this functioning today on your end?

Yes, everything works. I don't know what is wrong, but it will never work until you fix it to behave like this: The response you get when listing `/list-objects` with the CF Function enabled should be the same as the response you get when listing `/` with CF function disabled.

**Comment by MatthewCloudza** [comment]
Hi @x3LPh0r would like to know a bit more how you got this working please, really need help. Not sure if my settings are correct
Any way we could have a virtual call perhaps?

**Comment by x3LPh0r** [comment]
> Hi @x3LPh0r would like to know a bit more how you got this working please, really need help. Not sure if my settings are correct Any way we could have a virtual call perhaps?

Feel free to email me and we can discuss further there.
