### ISSUE TITLE
Feature Request: Search Behavior

### ISSUE THREAD

**Issue by x3LPh0r** [qoomon/aws-s3-bucket-browser#55]
First, I really love this interface. Nice clean and functional. I am noticing with the search however that it does not find directories (perhaps files as well) when you search for a word or words, like a keyword or phrase, that is in the center or end of the directory. It only will return the results of the search if you get the spelling/capitalization exactly correct from left to right. For example:

First Word_Second Word_Third/

if you search for Word here you do not get results. If you search for Third you do not get results. If you search any word after "First" you do not get results. You only get results if the words are typed correctly in order from left to right.

I am requesting a more fluid search behavior that returns results based on the word(s) regardless of capitalization and location in a name if that makes sense.

**Comment by qoomon** [comment]
Hi @x3LPh0r, sadly that's not possible, 'cause the is no s3 api to search like this. (at least I'm not aware of any).
S3 only supports `search by prefix`
