### ISSUE TITLE
Restrict permissions 

### ISSUE THREAD

**Issue by planetahuevo** [qoomon/aws-s3-bucket-browser#8]
Hi, 
Amazing project. Thanks! 

I am trying to figure out how to add a little layer of security not allowing public access but just limit the view to my hosted html. 

Not sure how to achieve this. 
I am thinking if we can limit the permissions so it will only work form my IP (where the hosted file is) or something like that. 

Do you have any suggestions on how to do this?

**Comment by qoomon** [comment]
You may configure a Bucket Policy, see following aws documentation.
* https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html
* https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-bucket-policy.html
Is that what you are looking for?

**Comment by planetahuevo** [comment]
That may be a solution. I will need to do some tests. The idea is that have list open to anyone is something I am not that comfortable with. 
I will let you know what I end up using. 
Thanks!

**Comment by qoomon** [comment]
You are right it highly depends on the use case.
